language: haskell

env:
 - GHCVER=8.0.2

addons:
  apt:
    packages:
      - libgmp-dev

cache:
  directories:
    - $HOME/.stack
   
before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack config set system-ghc --global true
- export PATH=/opt/ghc/8.0.2/bin:$PATH

install:
 - stack setup
 - stack install
